apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlltVm5jbVZoZERrNU9uZGxiR052YldVd01Tbz0iCgkJfQoJfQp9
kind: Secret
metadata:
  name: dockercreds
  namespace: preprod
type: kubernetes.io/dockerconfigjson
